# Generated by Django 3.1.4 on 2021-07-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='actualizado_el',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='ecommerce.Categorias', verbose_name='Categorias'),
        ),
    ]
