# Generated by Django 3.1.4 on 2021-07-02 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0002_auto_20210702_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
