# Generated by Django 3.1.4 on 2021-07-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20210705_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='ecommerce.Categorias', verbose_name='Categorias'),
        ),
    ]
