# Generated by Django 3.1.4 on 2021-07-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20210705_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categorias', verbose_name='Categorias'),
            preserve_default=False,
        ),
    ]
