# Generated by Django 3.1.4 on 2021-07-06 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0009_auto_20210705_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.FloatField()),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('lista_productos', models.ManyToManyField(to='ecommerce.Productos', verbose_name='Carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'ordering': ['-creado_el'],
            },
        ),
    ]
