# Generated by Django 3.1.4 on 2021-07-07 02:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0011_auto_20210706_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrito',
            new_name='Carritos',
        ),
    ]
